#kubectl -n app logs -f $(kubectl -n app get pods --field-selector status.phase=Running --no-headers -o custom-columns=":metadata.name" | grep simple-news-web | head -1)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-news-web
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-news-web
  template:
    metadata:
      labels:
        app: simple-news-web
    spec:
      containers:
        - name: simple-news-web
          image: simple-news:v1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir: {}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: simple-news-service
  namespace: app
  labels:
    app: simple-news-web
spec:
  ports:
    - port: 8080 # between containers for service call for K8s
      targetPort: 8080 # container port
      nodePort: 30080 # by default >30000 for external call
  type: NodePort
  selector:
    app: simple-news-web


