DROP TABLE IF EXISTS shedlock;

CREATE TABLE shedlock(
  name VARCHAR(64) NOT NULL,
  lock_until TIMESTAMP(3) NOT NULL,
  locked_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  locked_by VARCHAR(255) NOT NULL,
  PRIMARY KEY (name)
);

DROP TABLE IF EXISTS CITY;
CREATE TABLE CITY (
    City_code INT AUTO_INCREMENT  PRIMARY KEY,
    city_name VARCHAR(50) NOT NULL,
    city_pincode INT(8) NOT NULL
);
